# Puerto en el que correrá Spring Boot
server.port=8082

# Tu URI real de conexión a MongoDB Atlas (Corregida con nicolaspaez929_db_user)
spring.data.mongodb.uri=mongodb+srv://nicolaspaez929_db_user:Mashle2026@pokemongo.f65pksm.mongodb.net/

# El nombre exacto de la base de datos donde insertaste los datos
spring.data.mongodb.database=pokedex